applications:
  - name: domain-fraud
    health-check-type: http
    health-check-http-endpoint: /actuator/health
    env:
      SPRING_PROFILES: default

Feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000